# This file is needed in order to pass an NPM_TOKEN so that the builder can
# access our private repos
steps:
# build all the way
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_APP_NAME-build:latest',
    '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME',
    '--build-arg', 'NPM_TOKEN=$_NPM_TOKEN',
    '.']

images: []
